# Generated by Django 3.2.13 on 2022-05-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name_plural': 'User follows'},
        ),
    ]
