# Generated by Django 3.2.13 on 2022-05-29 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='titre')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=post.models.ticket_picture_path, verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
